version: '3'

services:

  nginx:

    build:
        context: .
        dockerfile: nginx.dockerfile
        args:
          - NGINX_VERSION=${NGINX_VERSION}

    image: ${NGINX_CONTAINER_NAME}:${NGINX_VERSION}
    
    container_name: ${NGINX_CONTAINER_NAME}

    depends_on:
      - go

    ports:
       - ${NGINX_PORT}:80

    stdin_open: true
    tty: true

  mongo:

    image: mongo:${MONGO_VERSION}

    container_name: ${MONGO_CONTAINER_NAME}

    stdin_open: true
    tty: true

  go:

      build:
        context: .
        dockerfile: go.dockerfile
        args:
          - PROJECT_NAME=${PROJECT_NAME}
          - GO_VERSION=${GO_VERSION}
          - GO_PORT=${GO_PORT}

      image: ${GO_CONTAINER_NAME}:${GO_VERSION}
      
      container_name: $GO_CONTAINER_NAME
      
      volumes:
        - $PROJECTS_HOME/$PROJECT_NAME:/go/src/$PROJECT_NAME

      depends_on: 
        - mongo

      environment:

          ## HOST ENVIRONMENT VARIABLES
          ## GITHUB_CLIENT_SECRET
          ## GITHUB_CLIENT_ID

        - GITHUB_CLIENT_ID
        - GITHUB_CLIENT_SECRET
        - LISTENING_ADDRESS
        - MONGO_ADDRESS

      stdin_open: true
      tty: true
