version: '3'

services:

  jenkins:

    image: jenkins

    container_name: jenkins

    ports:
      - 80:8080
      - 50000:50000

    volumes:
      - jenkins-data:/var/jenkins_home

  go:

    image: registry.gitlab.com/marco2704/zeus/go-base:1.8

    command: ["go", "run", "main.go"]

    container_name: zeus-go

    volumes:
      ## Context absolute path must match with /go/src/github.com/marco2704

      - ${PWD}:${PWD}

    depends_on:
      - redis
      - mongo

    ports:
      - 8080:8080

    environment:
      ## Both have to be host environment variables such as they will be
      ## automatically set as same in the container.

      - GITHUB_CLIENT_ID
      - GITHUB_CLIENT_SECRET

    stdin_open: true
    tty: true

  redis:

    image: redis:4.0

    container_name: zeus-redis

    ports:
      - 6379:6379

    stdin_open: true
    tty: true

  mongo:

    image: mongo:3.4

    container_name: zeus-mongo

    ports:
      - 27017:27017

    stdin_open: true
    tty: true

volumes:
  jenkins-data:
