version: '3'

services:

  nginx:

    build:
        context: docker
        dockerfile: docker/nginx.dockerfile
        args:
          - NGINX_VERSION=${NGINX_VERSION}

    image: zeus-nginx:${NGINX_VERSION}
    
    container_name: zeus-nginx

    depends_on:
      - go

    ports:
       - ${NGINX_PORT}:80

    stdin_open: true
    tty: true

  redis:

    image: redis:${REDIS_VERSION}

    container_name: zeus-redis

    stdin_open: true
    tty: true

  mongo:

    image: mongo:${MONGO_VERSION}

    container_name: zeus-mongo

    ports:
      - ${MONGO_PORT}:${MONGO_PORT}

    stdin_open: true
    tty: true

  go:

      build:
        context: docker
        dockerfile: docker/go.build
        args:
          - GO_VERSION=${GO_VERSION}

      image: zeus-go:${GO_VERSION}
      
      container_name: zeus-go
      
      volumes:
        - ${PWD}:${PWD}

      depends_on:
        - redis
        - mongo

      environment:

        ## HOST ENVIRONMENT VARIABLES
        ## GITHUB_CLIENT_SECRET
        ## GITHUB_CLIENT_ID

        - GITHUB_CLIENT_ID
        - GITHUB_CLIENT_SECRET
        - REDIS_ADDRESS
        - MONGO_PORT
        - MONGO_ADDRESS=mongo:${MONGO_PORT}

      stdin_open: true
      tty: true
