version: '3'

services:
  
  zeus-mongo:

    image: mongo:3.4

    container_name: zeus-mongo3.4

    ports:
      - 27017:27017

    stdin_open: true
    tty: true

  zeus-go:

      build:
        context: .
        dockerfile: go.dockerfile
        args:
          - PROJECT_NAME=zeus
          - CODE_VERSION=1.9
          - GO_PORT=8080

      
      image: zeus-go:1.9
      
      container_name: zeus-go1.9
      
      volumes:
        - ~/Projects/go/src/zeus:/go/src/zeus

      environment:
        - MONGO_ADDRESS=mongo:27017

      depends_on: 
        - zeus-mongo
      
      links:
        - zeus-mongo:mongo

      ports:
        - 8080:8080

      stdin_open: true
      tty: true