version: '3'

services:

  nginx:

    build:
        context: .
        dockerfile: nginx.dockerfile
        args:
          - NGINX_VERSION=${NGINX_VERSION}

    image: ${NGINX_CONTAINER_NAME}:${NGINX_VERSION}
    
    container_name: ${NGINX_CONTAINER_NAME}

    depends_on:
      - go

    ports:
       - ${NGINX_PORT}:80

    stdin_open: true
    tty: true

  redis:

    image: redis:${REDIS_VERSION}

    container_name: ${REDIS_CONTAINER_NAME}

    stdin_open: true
    tty: true

  zeus-mongo:

    image: mongo:3.4

    container_name: zeus-mongo3.4

    ports:
      - "27017:27017"

    stdin_open: true
    tty: true

  go:

      build:
        context: .
        dockerfile: go.dockerfile
        args:
          - PROJECT_NAME=${PROJECT_NAME}
          - GOPATH=${GOPATH}
          - GO_VERSION=${GO_VERSION}
          - GO_PORT=${GO_PORT}
          - PROJECT_CONTAINER_PATH=${PROJECT_CONTAINER_PATH}

      image: ${GO_CONTAINER_NAME}:${GO_VERSION}
      
      container_name: $GO_CONTAINER_NAME
      
      volumes:
        - ${PROJECT_HOST_PATH}:${PROJECT_CONTAINER_PATH}

      depends_on:
        - redis

      environment:

        ## HOST ENVIRONMENT VARIABLES
        ## GITHUB_CLIENT_SECRET
        ## GITHUB_CLIENT_ID

        - GITHUB_CLIENT_ID
        - GITHUB_CLIENT_SECRET
        - LISTENING_ADDRESS
        - REDIS_ADDRESS

      stdin_open: true
      tty: true
